name: shop_management_system
description: A comprehensive shop management system with multiple modules
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  fl_chart: ^0.63.0
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
